version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: credit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: credit_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - credit-network

networks:
  credit-network:
    driver: bridge

volumes:
  mysql-data: